
spring:
  datasource:
    username: growandpull
    password: Gkd73lisbfl9
    url: jdbc:mysql://growandpull.ctegro5wnfvo.us-east-1.rds.amazonaws.com:3306/growandpull
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        globally_quoted_identifiers: true
        jdbc:
          time_zone: UTC
server:
  port: 8000
jwt:
  secret: 7538782F413F4428472B4B6250655368566D5971337336763979244226452948
  #  access_expiration: 10000
  #  access_expiration: 3600000
  access_expiration: 2629743000
  refresh_expiration: 86400000
paypal:
  client:
    id: AYHyuPYGWqDVXIWrXymJ8qqOzzNw-qs8AXMMjpU__zArxYDfWItT5ErSvBpx3YxQhza3Ztp1K8bOuGVj
    secret: EH4ridPPanq4ePYTrtVFG-qPDctdKXSWv951g6tFsMpAlfdJunlcFXpWP_JQR4gmAmPs-4oLksIuANjK
  url:
    return: http://localhost:3000/capture
    cancel: http://localhost:3000/cancel

#  forward-headers-strategy: framework
#springdoc:
#  api-docs:
#    path: /docs
#  swagger-ui:
#    path: /docs.html