
spring:
  datasource:
    username: growandpull
    password: Gkd73lisbfl9
    url: jdbc:mysql://growandpull.ctegro5wnfvo.us-east-1.rds.amazonaws.com:3306/growandpull
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        globally_quoted_identifiers: true
server:
  port: 8000
#  forward-headers-strategy: framework
#springdoc:
#  api-docs:
#    path: /docs
#  swagger-ui:
#    path: /docs.html
